modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

# Adicione esta linha. É a mais importante.
# Ela diz ao servidor para permitir que jogadores sem o mod se conectem.
displayTest="IGNORE_SERVER_VERSION"

[[mods]]
modId="legendsarena"
version="1.0.0"
displayName="Legends Arena"
description='''
Um sistema de batalhas ranqueadas para servidores Pixelmon.
'''

[[dependencies.legendsarena]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.legendsarena]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"